# Generated by Django 5.0.3 on 2024-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.AlterField(
            model_name='crew',
            name='crewName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
