# Generated by Django 5.0.3 on 2024-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
