# Generated by Django 5.0.3 on 2024-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_duedate_alter_task_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
